name: brain
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab
  - matplotlib
  - numpy
  - pip
  - pandas
  - python
  - scikit-learn
  - spyder
  - tensorflow-gpu
  - pip:
    - imutils
    - opencv-python
